name: Laravel

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Copy .env
    - name: SCP files
      uses: bamlhs/deploy-via-scp@master
      run: ls -alh
      run: pwd
      with:
        local: "*" # eg: dist
        remote: ${{ secrets.REMOTE }} # eg: /home/github-action
        host: ${{ secrets.HOST }} # eg: example.com
        port: ${{ secrets.PORT }} # eg: 22
        user: ${{ secrets.USERNAME }} # eg: github-action
        key: ${{ secrets.KEY }}